=== thomharry76320/Projet-XML/src/main/resources/cv24.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://univ.fr/cv24" xmlns="http://univ.fr/cv24"
           elementFormDefault="unqualified">

    <!-- Element -->
    <xs:element name="cv24" type="cv24"></xs:element>
    <xs:element name="identite" type="identiteType" ></xs:element>
    <xs:element name="objectif" type="objectifType"></xs:element>
    <xs:element name="prof" type="profType"></xs:element>
    <xs:element name="competences" type="competencesType"></xs:element>
    <xs:element name="divers" type="diversType"></xs:element>

    <xs:complexType name="cv24">
        <xs:all>
            <xs:element ref="identite" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element ref="objectif" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element ref="prof" minOccurs="0" maxOccurs="1"></xs:element>
            <xs:element ref="competences"  minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element ref="divers" minOccurs="0" maxOccurs="1"></xs:element>
        </xs:all>
    </xs:complexType>

    <!-- Represente la section identité du CV -->
    <xs:complexType name="identiteType">
        <xs:sequence>
            <xs:element name="genre" type="genreType" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="nom" type="texteMaj32" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="prenom" type="texte32" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="tel" type="telType" minOccurs="0" maxOccurs="1"></xs:element>
            <xs:element name="mail" type="Fmail" minOccurs="0" maxOccurs="1"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Represente les différents genre possbile -->
    <xs:simpleType name="genreType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Mme"></xs:enumeration>
            <xs:enumeration value="M."></xs:enumeration>
            <xs:enumeration value="Miss"></xs:enumeration>
            <xs:enumeration value="Mrs"></xs:enumeration>
            <xs:enumeration value="Mr"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <!-- Represente le format des emails -->
    <xs:simpleType name="Fmail">
        <xs:restriction base="xs:string">
            <xs:maxLength value="128"></xs:maxLength>
            <xs:pattern value="[\p{L}\p{Nd}_-]+([\p{L}\p{Nd}_-]|\.([\p{L}\p{Nd}_-]))+@[^\.]([\p{L}\p{Nd}_-]|\.([\p{L}\p{Nd}_-]))+(\.[a-zA-Z]{2,3})"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Represente le format des numéros de téléphone -->
    <xs:simpleType name="telType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\d{10})|(\d{2}\s\d{2}\s\d{2}\s\d{2}\s\d{2})|(\d\s\d{3}\s\d{3}\s\d{3})|(\+33\s\d\s\d{2}\s\d{2}\s\d{2}\s\d{2})"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- Represente la section obectif du CV -->
    <xs:complexType name="objectifType">
        <xs:sequence>
            <xs:element name="objectif" type="texte128" minOccurs="1" maxOccurs="1"></xs:element>
        </xs:sequence>
        <xs:attribute name="status" use="required">
            <xs:simpleType >
                <xs:restriction base="xs:string">
                    <xs:enumeration value="emploi"></xs:enumeration>
                    <xs:enumeration value="stage"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <!-- Represente la section prof du CV -->
    <xs:complexType name="profType">
        <xs:sequence>
            <xs:element name="detail" type="detailType" minOccurs="1" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="detailType">
        <xs:sequence>
            <xs:element name="datedeb" type="xs:date" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="datefin" type="xs:date" minOccurs="0" maxOccurs="1"></xs:element>
            <xs:element name="titre" type="texte128" minOccurs="1" maxOccurs="1"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Represente la section compétences du CV -->
    <xs:complexType name="competencesType">
        <xs:sequence>
            <xs:element name="diplôme" type="detaildiplome" minOccurs="1" maxOccurs="5"></xs:element>
            <xs:element name="certif" type="certifType" minOccurs="0" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="detaildiplome">
        <xs:sequence>
            <xs:element name="date" type="xs:date" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="institut" type="texte32" minOccurs="0" maxOccurs="1"></xs:element>
            <xs:element name="titre" type="texte32" minOccurs="1" maxOccurs="5"></xs:element>
        </xs:sequence>
        <xs:attribute name="niveau" type="niveauType" use="required"></xs:attribute>
    </xs:complexType>

    <!-- Force les valeurs de niveau entre 1 et 8 -->
    <xs:simpleType name="niveauType">
        <xs:restriction base="xs:int">
            <xs:maxInclusive value="8"></xs:maxInclusive>
            <xs:minInclusive value="1"></xs:minInclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="certifType">
        <xs:sequence>
            <xs:element name="datedeb" type="xs:date" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="datefin" type="xs:date" minOccurs="0" maxOccurs="1"></xs:element>
            <xs:element name="titre" type="texte32" minOccurs="1" maxOccurs="1"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Represente la section divers du CV -->
    <xs:complexType name="diversType">
        <xs:sequence>
            <xs:element name="lv" type="lvType" minOccurs="1" maxOccurs="5"></xs:element>
            <xs:element name="autre" type="autreType" minOccurs="0" maxOccurs="3"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="autreType">
        <xs:attribute name="titre" type="texte32" use="required"></xs:attribute>
        <xs:attribute name="comment" type="texte128" use="optional"></xs:attribute>
    </xs:complexType>


    <xs:complexType name="lvType">
        <xs:attribute name="lang" type="xs:string" use="required"></xs:attribute>
        <xs:attribute name="cert" type="certifiType" use="required"></xs:attribute>
        <xs:attribute name="nivs" type="nivType" use="optional"></xs:attribute>
        <xs:attribute name="nivi" type="niviType" use="optional"></xs:attribute>
    </xs:complexType>

    <xs:simpleType name="formatlang">
        <xs:restriction base="xs:string">
            <xs:maxLength value="2"></xs:maxLength>
            <xs:pattern value="[a-z]{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="certifiType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MAT"></xs:enumeration>
            <xs:enumeration value="CLES"></xs:enumeration>
            <xs:enumeration value="TOEIC"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nivType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A1"></xs:enumeration>
            <xs:enumeration value="A2"></xs:enumeration>
            <xs:enumeration value="B1"></xs:enumeration>
            <xs:enumeration value="B2"></xs:enumeration>
            <xs:enumeration value="C1"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="niviType">
        <xs:restriction base="xs:int">
            <xs:maxInclusive value="990"></xs:maxInclusive>
            <xs:minInclusive value="10"></xs:minInclusive>
        </xs:restriction>
    </xs:simpleType>

    <!-- SECTION FORMAT TEXTE -->
    <!-- Represente les textes au format String32Maj -->
    <xs:simpleType name="texteMaj32">
        <xs:restriction base="xs:string">
            <xs:maxLength value="32"></xs:maxLength>
            <xs:pattern value="[\p{Lu}\s'\-]{1,32}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Represente les textes au format String32 -->
    <xs:simpleType name="texte32">
        <xs:restriction base="xs:string">
            <xs:maxLength value="32"></xs:maxLength>
            <xs:pattern value="[\p{L}\s'\-]{1,32}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Represente les textes au format String128 -->
    <xs:simpleType name="texte128">
        <xs:restriction base="xs:string">
            <xs:maxLength value="128"></xs:maxLength>
            <xs:pattern value="[\p{L}\p{Nd}\s.,:;'@()-=_*~$?!#&amp;]{1,128}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== thomharry76320/Projet-XML/src/test/resources/goodCv.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv24:cv24 xmlns:cv24="http://univ.fr/cv24" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/cv24 cv24.xsd ">
    <cv24:identite>
        <genre>Mr</genre>
        <nom>OLIVIER</nom>
        <prenom>THOMAS</prenom>
        <tel>+33 1 23 45 67 89</tel>
        <mail>thomas@gmail.com</mail>
    </cv24:identite>
    <cv24:objectif status="stage">
        <objectif>AAAadjajoiqjfia1141412389.,':;@~$#()&amp;?!$*-_=</objectif>
    </cv24:objectif>
    <cv24:prof>
        <detail>
            <datedeb>2024-04-11</datedeb>
            <datefin>2024-04-11</datefin>
            <titre>mangeur de hot-dog</titre>
        </detail>
    </cv24:prof>
    <cv24:competences>
        <diplôme niveau="5">
            <date>2024-04-11</date>
            <institut>fhuadfh	faoiuzepeggzgezgeezgzhçf</institut>
            <titre>bac</titre>
            <titre>licence</titre>
            <titre>master</titre>
            <titre>doctorat</titre>
            <titre>iron man</titre>

        </diplôme>
        <certif>
            <datedeb>2024-04-11</datedeb>
            <datefin>2024-04-11</datefin>
            <titre>afu</titre>
        </certif>
        <certif>
            <datedeb>2024-04-11</datedeb>
            <titre>afu</titre>
        </certif>
        <certif>
            <datedeb>2024-04-11</datedeb>
            <titre>fhuadfh	faoiuzepeggzgezgeezgzhçf</titre>
        </certif>
        <certif>
            <datedeb>2024-04-11</datedeb>
            <datefin>2024-04-11</datefin>
            <titre>afu</titre>
        </certif>
    </cv24:competences>
    <cv24:divers>
        <lv lang="fr" cert="CLES" nivs="B1"/>
        <autre titre="sportif de haut niveau" comment="natation"></autre>
    </cv24:divers>
</cv24:cv24>

=== thomharry76320/Projet-XML/src/main/resources/cvComplet.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv24:cv24 xmlns:cv24="http://univ.fr/cv24" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/cv24 cv24.xsd ">
    <cv24:identite>
        <genre>Mr</genre>
        <nom>OLIVIER</nom>
        <prenom>THOMAS</prenom>
        <tel>+33 1 23 45 67 89</tel>
        <mail>thomas@gmail.com</mail>
    </cv24:identite>
    <cv24:objectif status="stage">
        <objectif>AAAadjajoiqjfia1141412389.,':;@~$#()&amp;?!$*-_=</objectif>
    </cv24:objectif>
    <cv24:prof>
        <detail>
            <datedeb>2021-12-04</datedeb>
            <datefin>2022-03-10</datefin>
            <titre>promeneur de chien</titre>
        </detail>
        <detail>
            <datedeb>2021-12-04</datedeb>
            <datefin>2012-03-08</datefin>
            <titre>promeneur de chien</titre>
        </detail>
        <detail>
            <datedeb>2021-12-04</datedeb>
            <datefin>2022-03-10</datefin>
            <titre>promeneur de chat</titre>
        </detail>
    </cv24:prof>
    <cv24:competences>
        <diplôme niveau="5">
            <date>2024-04-11</date>
            <institut>fhuadfh	faoiuzepeggzgezgeezgzhçf</institut>
            <titre>bac</titre>
            <titre>licence</titre>
            <titre>master</titre>
            <titre>doctorat</titre>
            <titre>jedi</titre>
        </diplôme>
        <diplôme niveau="5">
            <date>2024-04-12</date>
            <institut>fhuadfh	faoiuzepeggzgezgeezgzhçf</institut>
            <titre>bac</titre>
            <titre>licence</titre>
            <titre>master</titre>
            <titre>doctorat</titre>
            <titre>jedi</titre>
        </diplôme>
        <diplôme niveau="4">
            <date>2024-04-11</date>
            <institut>fhuadfh	faoiuzepeggzgezgeezgzhçf</institut>
            <titre>bac</titre>
            <titre>licence</titre>
            <titre>master</titre>
            <titre>doctorat</titre>
            <titre>jedi</titre>
        </diplôme>
        <diplôme niveau="2">
            <date>2024-04-11</date>
            <institut>fhuadfh	faoiuzepeggzgezgeezgzhçf</institut>
            <titre>bac</titre>
            <titre>licence</titre>
            <titre>master</titre>
            <titre>doctorat</titre>
            <titre>jedi</titre>
        </diplôme>
        <diplôme niveau="1">
            <date>2024-04-11</date>
            <institut>fhuadfh	faoiuzepeggzgezgeezgzhçf</institut>
            <titre>bac</titre>
            <titre>licence</titre>
            <titre>master</titre>
            <titre>doctorat</titre>
            <titre>jedi</titre>
        </diplôme>
        <certif>
            <datedeb>2024-04-11</datedeb>
            <titre>fhuadfh	faoiuzepeggzgezgeezgzhçf</titre>
        </certif>
        <certif>
            <datedeb>2024-04-11</datedeb>
            <datefin>2024-04-11</datefin>
            <titre>afu</titre>
        </certif>
    </cv24:competences>
    <cv24:divers>
        <lv lang="fr" cert="CLES" nivs="B1"/>
        <lv lang="en" cert="MAT" />
        <lv lang="es" cert="TOEIC" nivi="100"/>
        <lv lang="fn" cert="CLES" nivs="A2"/>
        <lv lang="po" cert="MAT"/>
        <autre titre="sportif de haut niveau" comment="natation"></autre>
        <autre titre="sportif de haut niveau" comment="foot"></autre>
        <autre titre="sportif de haut niveau" comment="tennis"></autre>
    </cv24:divers>
</cv24:cv24>

=== thomharry76320/Projet-XML/src/main/resources/cvMinimal.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv24:cv24 xmlns:cv24="http://univ.fr/cv24" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/cv24 cv24.xsd ">
    <cv24:identite>
        <genre>Mr</genre>
        <nom>OLIVIER</nom>
        <prenom>THOMAS</prenom>
        <tel>06 12 17 14 12</tel>
    </cv24:identite>
    <cv24:objectif status="stage">
        <objectif>AAAadjajoiqjfia1141412389.,':;@~$#()&amp;?!$*-_=</objectif>
    </cv24:objectif>
    <cv24:competences>
        <diplôme niveau="5">
            <date>2024-04-11</date>
            <titre>bac</titre>
        </diplôme>
    </cv24:competences>
</cv24:cv24>
